// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effectiveness } from "./Effectiveness";

/**
 * Claude bridge installation and behavioral status.
 */
export type BridgeStatus = {
/**
 * Whether Claude settings currently invoke our bridge.
 */
installed: boolean,
/**
 * Whether the bridge invokes an earlier configured command.
 */
chained: boolean,
/**
 * Behavioral confidence that Claude is invoking the bridge.
 */
effective: Effectiveness,
/**
 * Claude settings path shown in diagnostics.
 */
settingsPath: string, };
