// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenCount } from "./TokenCount";
import type { UnixSeconds } from "./UnixSeconds";

/**
 * One token-history bucket.
 */
export type Bucket = {
/**
 * Bucket start time.
 */
start: UnixSeconds,
/**
 * Tokens counted in the bucket.
 */
tokens: TokenCount, };
