// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of bounded Codex executable detection.
 */
export type CodexDetection = {
/**
 * Resolved executable path, if found.
 */
path: string | null,
/**
 * Bounded `codex --version` output, if executable probing succeeded.
 */
version: string | null, };
