// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public, deliberately bounded error returned by every Tauri command.
 */
export type CommandError = {
/**
 * Safe user-facing failure summary.
 */
message: string, };
