// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Connection and data-health state for a provider source.
 */
export type ConnectionStatus = { "state": "connected" } | { "state": "stale" } | { "state": "degraded",
/**
 * A short user-facing explanation of the degraded mode.
 */
reason: string, } | { "state": "notConfigured",
/**
 * A short action the user can take.
 */
hint: string, } | { "state": "authExpired",
/**
 * A short action the user can take.
 */
hint: string, } | { "state": "unsupported",
/**
 * A short provider-facing explanation.
 */
reason: string, } | { "state": "error",
/**
 * A short actionable error message.
 */
message: string, };
