// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a surface shows paid usage (Claude extra usage, Codex credits).
 *
 * A provider with nothing to show (extra usage off, no Codex credits) keeps
 * showing its limit, even with [`CreditsDisplay::Only`].
 */
export type CreditsDisplay = "Off" | "WithLimits" | "Only";
