// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreditAmount } from "./CreditAmount";
import type { SourceKind } from "./SourceKind";
import type { UnixSeconds } from "./UnixSeconds";

/**
 * Paid usage beyond plan limits: Claude extra usage or Codex credits.
 */
export type Credits = {
/**
 * Claude: extra usage is turned on. Codex: the account has credits.
 */
enabled: boolean,
/**
 * Codex plans whose credits are unlimited.
 */
unlimited: boolean,
/**
 * Amount spent in the current billing period (Claude).
 */
used: CreditAmount | null,
/**
 * Spending cap for the current billing period (Claude).
 */
limit: CreditAmount | null,
/**
 * Remaining prepaid balance (Codex).
 */
balance: CreditAmount | null,
/**
 * The source that reported these credits.
 */
source: SourceKind,
/**
 * When the source observed these credits.
 */
observedAt: UnixSeconds, };
