// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An amount of money or provider credits, kept in exact minor units.
 */
export type CreditAmount = {
/**
 * The amount in minor units; the value is `minor / 10^exponent`.
 */
minor: number,
/**
 * Decimal places represented in `minor`.
 */
exponent: number,
/**
 * ISO 4217 currency code such as `USD`, or `None` for provider credits.
 */
currency: string | null, };
