// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Behavioral confidence that Claude Code is invoking the installed bridge.
 */
export type Effectiveness = "unverified" | "confirmed" | "likelyOverridden" | "headlessOnly";
