// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Projection } from "./Projection";
import type { Provider } from "./Provider";
import type { Series } from "./Series";

/**
 * Usage history for one provider.
 */
export type History = {
/**
 * The provider represented by this history.
 */
provider: Provider,
/**
 * Exactly 24 local-hour-aligned buckets, oldest first.
 */
hourly: Series,
/**
 * Exactly seven daily buckets, oldest first, subject to Codex UTC account rules.
 */
daily: Series,
/**
 * Weekly percentage-based pace projection, when sufficiently stable.
 */
projection: Projection | null, };
