// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Percent } from "./Percent";
import type { SourceKind } from "./SourceKind";
import type { UnixSeconds } from "./UnixSeconds";
import type { WindowKind } from "./WindowKind";

/**
 * The usage and reset state for one classified provider limit window.
 */
export type LimitWindow = {
/**
 * The classified duration.
 */
kind: WindowKind,
/**
 * The consumed percentage.
 */
used: Percent,
/**
 * The provider-reported reset time, when known.
 */
resetsAt: UnixSeconds | null,
/**
 * Whether the reset has passed without a fresh provider reading.
 */
resetPending: boolean,
/**
 * The source that supplied the displayed values.
 */
source: SourceKind,
/**
 * When the source observed this window.
 */
observedAt: UnixSeconds, };
