// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings field for which a native path is being selected.
 */
export type PathPurpose = "CodexBinary" | "CodexHome" | "ClaudeDir";
