// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A finite usage percentage clamped to the inclusive range 0 through 100.
 */
export type Percent = number;
