// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnixSeconds } from "./UnixSeconds";

/**
 * A linear forecast for a weekly usage window.
 */
export type Projection = {
/**
 * Projected percentage at the weekly reset; this may exceed 100.
 */
projectedPercentAtReset: number,
/**
 * When 100 percent is projected to be reached, if before reset.
 */
hitsLimitAt: UnixSeconds | null, };
