// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A usage provider supported by the application.
 */
export type Provider = "claude" | "codex";
