// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionStatus } from "./ConnectionStatus";
import type { LimitWindow } from "./LimitWindow";
import type { Provider } from "./Provider";
import type { SourceHealth } from "./SourceHealth";
import type { SourceKind } from "./SourceKind";
import type { UnixSeconds } from "./UnixSeconds";

/**
 * The complete derived usage view for one provider.
 */
export type ProviderUsage = {
/**
 * The provider represented by this view.
 */
provider: Provider,
/**
 * The display plan, such as `Pro` or `Max`, when known.
 */
plan: string | null,
/**
 * Derived windows, sorted as session, weekly, then other duration ascending.
 */
windows: Array<LimitWindow>,
/**
 * Provider-level health derived from source authority and freshness.
 */
status: ConnectionStatus,
/**
 * The source whose window set defines the derived view.
 */
authoritativeSource: SourceKind | null,
/**
 * The authoritative source's last successful update time.
 */
lastUpdated: UnixSeconds | null,
/**
 * One health entry per source configured for this provider.
 */
sources: Array<SourceHealth>, };
