// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hash routes hosted by the main window.
 */
export type Route = "Overview" | "Claude" | "Codex" | "Settings" | "Onboarding";
