// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bucket } from "./Bucket";
import type { HistoryScope } from "./HistoryScope";
import type { SourceKind } from "./SourceKind";
import type { UnixSeconds } from "./UnixSeconds";

/**
 * A chart series from one source and one scope.
 */
export type Series = {
/**
 * The sole source used for every bucket in this series.
 */
source: SourceKind,
/**
 * Whether the data represents this Mac or the complete account.
 */
scope: HistoryScope,
/**
 * Human-readable scope text shown beneath the chart.
 */
scopeLabel: string,
/**
 * When the underlying source was last refreshed.
 */
observedAt: UnixSeconds | null,
/**
 * Ordered, zero-filled chart buckets.
 */
buckets: Array<Bucket>, };
