// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrayStyle } from "./TrayStyle";
import type { WidgetSettings } from "./WidgetSettings";

/**
 * Versioned application settings shared with the UI.
 */
export type Settings = { 
/**
 * On-disk schema version.
 */
schemaVersion: number, 
/**
 * Whether the three-step first-run flow has completed.
 */
onboardingCompleted: boolean, 
/**
 * Optional Codex executable override.
 */
codexPath: string | null, 
/**
 * Optional Codex data-directory override.
 */
codexHome: string | null, 
/**
 * Optional Claude configuration-directory override.
 */
claudeDir: string | null, 
/**
 * Whether the consent-based Claude status-line bridge is enabled.
 */
claudeBridgeEnabled: boolean, 
/**
 * Reserved post-v1 OAuth toggle; ignored without the feature.
 */
claudeOauthEnabled: boolean, 
/**
 * Sorted, unique notification thresholds in 1 through 100.
 */
thresholds: Array<number>, 
/**
 * Whether a provider reset should produce a notification.
 */
notifyOnReset: boolean, 
/**
 * Whether the app starts at login.
 */
launchAtLogin: boolean, 
/**
 * Whether the app appears in the Dock.
 */
showDockIcon: boolean, 
/**
 * Whether the dashboard window floats above other windows.
 */
mainAlwaysOnTop: boolean, 
/**
 * Menu-bar presentation style.
 */
trayStyle: TrayStyle, 
/**
 * Floating-widget settings.
 */
widget: WidgetSettings, 
/**
 * Active polling interval, with a minimum of 60 seconds.
 */
pollActiveSecs: number, 
/**
 * Idle polling interval, with a minimum of 120 seconds.
 */
pollIdleSecs: number, };
