// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Settings } from "./Settings";

/**
 * Settings plus downgrade-safety metadata exposed to the UI.
 */
export type SettingsState = { 
/**
 * Effective in-memory settings.
 */
settings: Settings, 
/**
 * Whether saves are disabled because the disk schema is newer.
 */
readOnly: boolean, 
/**
 * Human-readable downgrade or recovery notice.
 */
notice: string | null, 
/**
 * Whether this build includes the Claude OAuth usage source.
 */
claudeOauthAvailable: boolean, };
