// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mechanism that provides usage information.
 */
export type SourceKind = "codexAppServer" | "codexRollout" | "claudeStatusline" | "claudeOAuth" | "claudeLocalLogs";
