// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionStatus } from "./ConnectionStatus";
import type { SourceKind } from "./SourceKind";
import type { UnixSeconds } from "./UnixSeconds";

/**
 * Health information for one configured source.
 */
export type SourceHealth = {
/**
 * The source being described.
 */
source: SourceKind,
/**
 * The source's own status, independent of provider-level fallback logic.
 */
status: ConnectionStatus,
/**
 * The last successful reading time.
 */
lastSuccess: UnixSeconds | null, };
