// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which limit window the menu bar shows for each provider.
 */
export type TrayWindow = "FiveHour" | "Weekly";
