// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderUsage } from "./ProviderUsage";
import type { UnixSeconds } from "./UnixSeconds";

/**
 * A point-in-time usage view for every supported provider.
 */
export type UsageSnapshot = {
/**
 * Claude usage.
 */
claude: ProviderUsage,
/**
 * Codex usage.
 */
codex: ProviderUsage,
/**
 * When this derived snapshot was generated.
 */
generatedAt: UnixSeconds, };
