// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetVariant } from "./WidgetVariant";

/**
 * Persisted floating-widget presentation and position.
 */
export type WidgetSettings = { 
/**
 * Whether the widget should be restored on startup.
 */
visible: boolean, 
/**
 * Saved physical x coordinate, if the user has positioned the widget.
 */
x: number | null, 
/**
 * Saved physical y coordinate, if the user has positioned the widget.
 */
y: number | null, 
/**
 * Active widget layout.
 */
variant: WidgetVariant, 
/**
 * Window opacity in the inclusive range 0.4 through 1.0.
 */
opacity: number, };
