// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which limit windows the floating widget shows for each provider.
 *
 * A provider without the chosen window shows the window it does have, labeled.
 */
export type WidgetWindows = "FiveHour" | "Weekly" | "Both";
