// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Floating-widget layout variants.
 */
export type WidgetVariant = "Pill" | "Stack" | "Mini";
