// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classified limit window. Classification uses duration rather than response position.
 */
export type WindowKind = { "kind": "session" } | { "kind": "weekly" } | { "kind": "other",
/**
 * The reported duration in minutes.
 */
minutes: number, };
