// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the three native windows addressable by commands.
 */
export type WindowTarget = "Main" | "Popover" | "Widget";
